### ISSUE TITLE
Example 6 doesn't work

### ISSUE THREAD

**Issue by danbillingham** [iKettles/framer-data-component.framerfx#19]
In the supplied examples number six doesn't work.

**Comment by iKettles** [comment]
Hey @danbillingham, could you describe what isn't working? It sounds like you may have an old version of the example project. You can get a new version here:
https://framer.com/projects/new?duplicate=fXHamZqD4CB4e80R0Ldu

**Comment by danbillingham** [comment]
Daniel Billingham has invited you to collaborate on the 'Search Data Component 
- Examples (copy)' project in Framer You’ve been invited to collaborate in 
Framer.
‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ 

 
<http://www.framer.com/?utm_source=iterable&utm_medium=email&utm_campaign=FR-owned-framer-web-invite>
Framer 
<https://www.framer.com/?utm_source=iterable&utm_medium=email&utm_campaign=FR-owned-framer-web-invite>


Daniel Billingham has invited you to the Search Data Component - Examples 
(copy) 
<https://login.framer.com/?invite=21d6ccba-ebcd-4208-918d-447f0ee1f063&amp;existing=false&amp;redirect=https%3A%2F%2Fframer.com%2Fprojects%2FnAdW00rVpRgLgW10Zz41?utm_source=iterable&utm_medium=email&utm_campaign=FR-owned-framer-web-invite>
 project in Framer.


Framer 
<https://www.framer.com/why-framer?utm_source=iterable&utm_medium=email&utm_campaign=FR-owned-framer-web-invite>
 is the best prototyping tool for teams. Accept your invitation and you’ll be 
able to:



 * Create interactive prototypes without code
 * Share prototypes with teammates and collaborate on ideas together so 
nothing gets lost in translation
 * Get quicker buy-in from stakeholders, better feedback during user testing, 
and one-click code for handoff to engineers


Join project 
<https://login.framer.com/?invite=21d6ccba-ebcd-4208-918d-447f0ee1f063&amp;existing=false&amp;redirect=https%3A%2F%2Fframer.com%2Fprojects%2FnAdW00rVpRgLgW10Zz41?utm_source=iterable&utm_medium=email&utm_campaign=FR-owned-framer-web-invite>



Framer B.V., Singel 258, 1016AB Amsterdam, Netherlands

See the web version 
<https://links.framer.email/e/evib?_t=8a025ebd74f9439c8d735d994082f8ec&_m=15df8383b4954dcca705e2b603f810c4&_e=WET_wBJH4XFmOP1m_0B6aku5G21EDyGO6vGuCCKWNSWWrGKGT62mTzE3Io_xVhZSCAKJ-AiP2im4ZT3Z3tQloOxoKS638Qy0LHPg3MHaJpUQrzayRqWDNl441YMa5khP4eRcx80QZRovutcCoBUV3tXl1dGlFp8DNZpYgXE-9l2HDCrDyHYyThq79Oal8qCD>
 of this email

**Comment by danbillingham** [comment]
Hi Thanks for getting in touch.

I may be missing something, but I have taken the latest link you sent over and connected the input and search results overrides (from example 5) to example 6. 

But unlike the other examples when I perform a search in example six nothing happens.

I Invited you to the project.

I do think this is an awesome component by the way - great job. I would love to be able to tweak the results - even just to up the minMatchCharLength from 1 to 3 would go a long way to producing more realistic results.

**Comment by iKettles** [comment]
Hey @danbillingham, I think something may have went wrong with your invite. You can invite me directly using my email: iain@framer.com

The reason the search input wasn't having any effect was due to the presence of this function in the code component: 

```
onSearchData={(data: any, searchTerm: string) => {
    /**
      * This function is only called if search is enabled via the property controls
      * and a search term is present. It will be called for the initial fetch of the data,
      * whenever the search term changes, or when the sorting configuration is changed.
      *
      * This is a good place to override the default search behavior of the Data Component.
      * Internally, the Data Component uses Fuse.js to perform a fuzzy-match search. You may
      * want to do the same but instead use your own priority or exclude certain fields
      * from being searched.
      */

    return data
}}
```

When this function is present, the Data Component will bypass all of its default search behaviour, instead giving you the responsibility to perform the search. As this function didn't look at `props.searchTerm` (this is the input value that's made available to the component via a Code Override), this value wasn't being taken into account when searching the data. I've just updated the example project, that function is now commented out which retains the default search behaviour.

Great to hear the component is useful for you! I've just seen your ticket on Canny — I'm going to add a property that allows you to pass along a Fuse.js config so you can configure this as you wish. I'm going to close this ticket, but feel free to reach out to me directly if you need any more help.
