### ISSUE TITLE
Feature: Support nested JSON structures

### ISSUE THREAD

**Issue by vschmid** [iKettles/framer-data-component.framerfx#2]
Hey Ian, 
first of all, thanks for this great component! 
I am really interested in using this component to connect my designs with an API. Together with a Backend developer we tried various versions of his API and had some troubles with more complex JSON files. 

It seems like the plugin currently only supports non-nested JSON structures, are there any plans to add support for deeper objects? e.g.
{ “data”: [{“name”: “Anna”, “address”: {“street”: “Rue Gambetta”, “number”: “14a”, “city”: “Baguette”

**Comment by iKettles** [comment]
Hey @vschmid thanks for your message!

This is a great question. There are some challenges with dealing with nested data structures, due to the fact the names you give in Framer's design component overrides panel need to be converted into a valid string that can be used for a JavaScript variable's name. Which means using a jsonpath selector like this:
`$.data.address.city`
Would get transformed into:
`$data_address_city`

Which means you end up having collisions with variables that include underscores. I'd like to avoid that happening, so here's some potential paths forward:
- You fork this project and publish your own version of the Data Component as a private team package, where the flattening of the data is done in your code
- We add some kind of special path syntax to allow you to target nested fields, perhaps like so where a double underscore denotes a new level of the JSON: `data__address__city`
- We add an `onFormatData` callback you can use in a Code Override/Code Component that allows you to flatten the fields to your liking.

I'll experiment a bit with the special path syntax to see how well that would work and will get back to you.

**Comment by iKettles** [comment]
Hey @vschmid, I looked into the a jsonpath selector to solve nested data and it gets a bit fiddly. Instead, I've added support for using a custom data adapter to solve this use case. This gives you full control over how data is formatted/searched/sorted, meaning you can flatten your nested data structure so you can just use the regular string selectors. Here's a code snippet, you can also see this in action in the [Example Project](https://framer.com/projects/new?duplicate=fXHamZqD4CB4e80R0Ldu)

```
import * as React from "react"
import { Frame, addPropertyControls, ControlType } from "framer"
// @ts-ignore
import { DataComponent } from "@framer/iain.data-component/code/DataComponent"

export type SortDirection = "ascending" | "descending"
export type SortKey = string | null

export function CustomDataComponent(props) {
    return (
        <DataComponent
            {...props}
            onSearchData={(data: any, searchTerm: string) => {
                /**
                 * This function is only called if search is enabled via the property controls
                 * and a search term is present. It will be called for the initial fetch of the data,
                 * whenever the search term changes, or when the sorting configuration is changed.
                 *
                 * This is a good place to override the default search behavior of the Data Component.
                 * Internally, the Data Component uses Fuse.js to perform a fuzzy-match search. You may
                 * want to do the same but instead use your own priority or exclude certain fields
                 * from being searched.
                 */

                return data
            }}
            onSortData={(
                data: any,
                sortDirection: SortDirection,
                sortKey: SortKey
            ) => {
                /**
                 * This function is called whenever data is fetched, a search is performed,
                 * the sort direction is changed, or the key you are sorting on has changed.
                 *
                 * The component only supports a single sort key, but this adapter could easily
                 * be extended to support multi-sort.
                 */
                return data.sort((a, b) => {
                    return 0
                })
            }}
            onFormatData={(data: any) => {
                /**
                 * This function is called every time data is received from your data source.
                 *
                 * This is a great opportunity to format your data, such as flattening your data structure,
                 * combining fields, generating dummy data, or filtering out irrelevant data.
                 *
                 * To see this in action, remove `.reverse()` from line 52. You'll then see your data in
                 * the opposite order to how it is shown now.
                 */
                return data.reverse()
            }}
        />
    )
}

CustomDataComponent.defaultProps = {
    ...DataComponent.defaultProps,
}

addPropertyControls(CustomDataComponent, DataComponent.propertyControls)
```

Let me know if you have any questions! I'll close this issue now, feel free to reopen if this doesn't solve your use case.
